"""empty message

Revision ID: 1edf460f3057
Revises: d27941e4bd88
Create Date: 2022-05-10 10:15:10.738123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1edf460f3057'
down_revision = 'd27941e4bd88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cat', sa.Column('human_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cat', 'human', ['human_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cat', type_='foreignkey')
    op.drop_column('cat', 'human_id')
    # ### end Alembic commands ###
